services:
  bgrfacile:
    image: registry.bgrfacile.com/bgrfacile:latest
    container_name: bgrfacile
    ports:
      - "80:80"
    networks:
      - traefik-network
    environment:
      - DOMAINE_NAME=${DOMAINE_NAME}
    labels:
      - traefik.enable=true
      - traefik.http.routers.bgrfacile.rule=Host(`${DOMAINE_NAME:-bgrfacile.com}`)
      - traefik.http.routers.bgrfacile.entrypoints=websecure
      - traefik.http.routers.bgrfacile.tls.certresolver=le

networks:
  traefik-network:
    external: true
    name: traefik-network